### PR TITLE
Dev/autorefresh devices

### PR DESCRIPTION
**Pull request by vaital3000**
auto-refresh toggle on devices page

https://github.com/yllibed/Zigbee2MqttAssistant/issues/35

### CODE REVIEW

**Comment by carldebilly** [comment]
@vaital3000 That's an exciting contribution!  Sorry for the delay to review it.

**Comment by carldebilly** [comment]
@vaital3000 That's a very good job.  Do you consider it ready for merge?  I see no problem merging it. :-)

**Comment by vaital3000** [comment]
It's good idea! It is possible to implement with SignalR, that isn't very difficult. I think I do it later.
I can do it in this branch.

**Comment by carldebilly** [comment]
No.  Let's merge it as-is -- since it's working well and it's already adding value to Z2MA :-).

**Comment by carldebilly** [comment]
@all-contributors please add vaital3000 to code

**Pull request merged**
